/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthorityIndexRouteImport } from './routes/authority.index'
import { Route as AuthorityClustersIdRouteImport } from './routes/authority.clusters.$id'
import { Route as AuthorityIssuesIndexRouteImport } from './routes/authority.issues.index'
import { Route as AuthorityIssuesIdRouteImport } from './routes/authority.issues.$id'
import { Route as ReportResultIdRouteImport } from './routes/report.result.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityIndexRoute = AuthorityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityClustersIdRoute = AuthorityClustersIdRouteImport.update({
  id: '/clusters/$id',
  path: '/clusters/$id',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityIssuesIndexRoute = AuthorityIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityIssuesIdRoute = AuthorityIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => AuthorityRoute,
} as any)
const ReportResultIdRoute = ReportResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => ReportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRouteWithChildren
  '/settings': typeof SettingsRoute
  '/authority/': typeof AuthorityIndexRoute
  '/authority/clusters/$id': typeof AuthorityClustersIdRoute
  '/authority/issues/$id': typeof AuthorityIssuesIdRoute
  '/report/result/$id': typeof ReportResultIdRoute
  '/authority/issues/': typeof AuthorityIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRouteWithChildren
  '/settings': typeof SettingsRoute
  '/authority': typeof AuthorityIndexRoute
  '/authority/clusters/$id': typeof AuthorityClustersIdRoute
  '/authority/issues/$id': typeof AuthorityIssuesIdRoute
  '/report/result/$id': typeof ReportResultIdRoute
  '/authority/issues': typeof AuthorityIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRouteWithChildren
  '/settings': typeof SettingsRoute
  '/authority/': typeof AuthorityIndexRoute
  '/authority/clusters/$id': typeof AuthorityClustersIdRoute
  '/authority/issues/$id': typeof AuthorityIssuesIdRoute
  '/report/result/$id': typeof ReportResultIdRoute
  '/authority/issues/': typeof AuthorityIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority'
    | '/discover'
    | '/map'
    | '/report'
    | '/settings'
    | '/authority/'
    | '/authority/clusters/$id'
    | '/authority/issues/$id'
    | '/report/result/$id'
    | '/authority/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/map'
    | '/report'
    | '/settings'
    | '/authority'
    | '/authority/clusters/$id'
    | '/authority/issues/$id'
    | '/report/result/$id'
    | '/authority/issues'
  id:
    | '__root__'
    | '/'
    | '/authority'
    | '/discover'
    | '/map'
    | '/report'
    | '/settings'
    | '/authority/'
    | '/authority/clusters/$id'
    | '/authority/issues/$id'
    | '/report/result/$id'
    | '/authority/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorityRoute: typeof AuthorityRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  MapRoute: typeof MapRoute
  ReportRoute: typeof ReportRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/': {
      id: '/authority/'
      path: '/'
      fullPath: '/authority/'
      preLoaderRoute: typeof AuthorityIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/clusters/$id': {
      id: '/authority/clusters/$id'
      path: '/clusters/$id'
      fullPath: '/authority/clusters/$id'
      preLoaderRoute: typeof AuthorityClustersIdRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/issues/': {
      id: '/authority/issues/'
      path: '/issues'
      fullPath: '/authority/issues/'
      preLoaderRoute: typeof AuthorityIssuesIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/issues/$id': {
      id: '/authority/issues/$id'
      path: '/issues/$id'
      fullPath: '/authority/issues/$id'
      preLoaderRoute: typeof AuthorityIssuesIdRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/report/result/$id': {
      id: '/report/result/$id'
      path: '/result/$id'
      fullPath: '/report/result/$id'
      preLoaderRoute: typeof ReportResultIdRouteImport
      parentRoute: typeof ReportRoute
    }
  }
}

interface AuthorityRouteChildren {
  AuthorityIndexRoute: typeof AuthorityIndexRoute
  AuthorityClustersIdRoute: typeof AuthorityClustersIdRoute
  AuthorityIssuesIdRoute: typeof AuthorityIssuesIdRoute
  AuthorityIssuesIndexRoute: typeof AuthorityIssuesIndexRoute
}

const AuthorityRouteChildren: AuthorityRouteChildren = {
  AuthorityIndexRoute: AuthorityIndexRoute,
  AuthorityClustersIdRoute: AuthorityClustersIdRoute,
  AuthorityIssuesIdRoute: AuthorityIssuesIdRoute,
  AuthorityIssuesIndexRoute: AuthorityIssuesIndexRoute,
}

const AuthorityRouteWithChildren = AuthorityRoute._addFileChildren(
  AuthorityRouteChildren,
)

interface ReportRouteChildren {
  ReportResultIdRoute: typeof ReportResultIdRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportResultIdRoute: ReportResultIdRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorityRoute: AuthorityRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  MapRoute: MapRoute,
  ReportRoute: ReportRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
